spring:
  application:
    name: OnlineStore
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300
    refreshTokenExpiration: 604800
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}




springdoc:
  api-docs:
    path: /api-docs
