spring:
  application:
    name: OnlineStore
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: zxc22331@NBnb!
    jpa:
      show-sql: true